# =====================================================
# Relevant Courseworks data displayed on the Homepage.
#
# This section lists relevant coursework taken at various institutions.
#
# ✔ The `title` field is the course title/number.
#
# ✔ The `institution` field indicates where the course was taught (Cornell, Harvard, MIT).
#
# ✔ The `term` field indicates when the course was taken (e.g., "Fall 2025").
#
# ✔ The `subjects` field is an array of subjects (e.g., ["CS", "Robotics", "ML", "AI"]).
# =====================================================

courseworks:

  - title: "MIT 2.12"
    institution: "MIT (Cross-Registration)"
    description: "Introduction to Robotics"
    term: "Spring 2026"
    subjects: ["CS", "Robotics"]

  - title: "COMPSCI 1440R"
    institution: "Harvard University"
    description: "Networks Design Projects"
    term: "Spring 2026"
    subjects: ["CS", "ML", "AI"]

  - title: "MIT 6.4212"
    institution: "MIT (Cross-Registration)"
    description: "Robotic Manipulation"
    term: "Fall 2025"
    subjects: ["CS", "Robotics", "ML", "AI"] 

  - title: "COMPSCI 1820"
    institution: "Harvard University"
    description: "Planning and Learning Methods for AI"
    term: "Fall 2025"
    subjects: ["CS", "Robotics", "AI", "ML"]

  - title: "ES 30"
    institution: "Harvard University"
    description: "Startups: From Idea to Exit"
    term: "Fall 2025"
    subjects: ["Entrepreneurship"]

  - title: "CS 3780"
    institution: "Cornell University"
    description: "Introduction to Machine Learning"
    term: "Spring 2025"
    subjects: ["CS", "ML", "AI"]

  - title: "INFO 1300"
    institution: "Cornell University"
    description: "Introductory Design and Programming for the Web"
    term: "Spring 2025"
    subjects: ["CS"]

  - title: "MAE 4900"
    institution: "Cornell University"
    description: "Independent Research"
    term: "Spring 2025"
    subjects: ["Research", "Robotics"]

  - title: "BEE 4990"
    institution: "Cornell University"
    description: "Independent Research"
    term: "Spring 2025, Spring 2024, Fall 2023"
    subjects: ["CS", "Research"]

  - title: "MATH 2940"
    institution: "Cornell University"
    description: "Linear Algebra for Engineers"
    term: "Spring 2025"
    subjects: ["Math"]

  - title: "MATH 2930"
    institution: "Cornell University"
    description: "Differential Equations for Engineers"
    term: "Summer 2024"
    subjects: ["Math"]

  - title: "CS 2110"
    institution: "Cornell University"
    description: "Object-Oriented Programming and Data Structures"
    term: "Summer 2024"
    subjects: ["CS"]

  - title: "CS 2800"
    institution: "Cornell University"
    description: "Discrete Structures"
    term: "Spring 2024"
    subjects: ["CS", "Math"]

  - title: "INFO 1260"
    institution: "Cornell University"
    description: "Choices and Consequences in Computing"
    term: "Spring 2024"
    subjects: ["CS"]

  - title: "MATH 1920"
    institution: "Cornell University"
    description: "Multivariable Calculus for Engineers"
    term: "Spring 2024"
    subjects: ["Math"]

  - title: "INFO 2040"
    institution: "Cornell University"
    description: "Networks"
    term: "Winter 2024"
    subjects: ["CS"]

  - title: "CS 1112"
    institution: "Cornell University"
    description: "Introduction to Computing: An Engineering and Science Perspective"
    term: "Fall 2023"
    subjects: ["CS"]

  - title: "MATH 1910"
    institution: "Cornell University"
    description: "Single Variable Calculus for Engineers"
    term: "Fall 2023"
    subjects: ["Math"]
