# =====================================================
# Data displayed on the Home (About Me) page.
#
# üí° Tip for Images / Logo:
# You can use either:
# 1. A full URL (e.g., https://example.com/logo.png)
# 2. A local file placed under /public/images/ and referenced with "/" (e.g., "/images/logo.png")
# =====================================================

# =====================================================
# üë§ Personal Information
# =====================================================

profile:
  name: "Youhui (Jeffrey) Wang"
  headline: "Undergraduate Student @ Harvard College | Cornell University"
  email: "jeffrey underline wang at college dot harvard dot edu"
  location: Cambridge, MA
  profileImage: "images/self.png"

  links:
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/youhuiwang/"
      icon:
        name: "FaLinkedin"
        package: "react-icons/fa6"

    - name: "Google Scholar"
      url: "https://scholar.google.com/citations?user=AtHsy-EAAAAJ&hl=zh-CN"
      icon:
        name: "FaGoogleScholar"
        package: "react-icons/fa6"

    - name: "R√©sum√©"
      url: ""
      icon:
        name: "FaRegIdBadge"
        package: "react-icons/fa6"

    - name: "Github"
      url: "https://github.com/JeffreyWang060303"
      icon:
        name: "FaGithub"
        package: "react-icons/fa6"

  # you can use HTML syntax here (e.g. <br/>, <a>, <strong>, ...)
  biography: |
    Hi! I'm <strong>Jeffrey Wang</strong>, currently a Visiting Undergraduate Student at <strong>Harvard College</strong>, originally from
    <strong>Cornell University</strong>, passionate about <em>Robotics learning, control, and Artificial Intelligence in general</em>. 
    Currently, I work as a <em>Research Intern</em> at the <strong>CogAI Lab</strong> under <strong>Stanford Aritficial 
    Intelligence Laboratory</strong>, fortunately advised by <strong>Raven Huang, Prof. Jiajun Wu, and Prof. Fei-fei Li</strong>,
    and <strong>Harvard Edge Computing Lab</strong>, fortunately advised by <strong>Jason Jabbour and Prof. Vijay Janapa Reddi</strong>.
    <div class="my-2"></div>
    <strong>Research Interests:</strong>
    <ul style="margin-top: 0.5rem; margin-bottom: 0.5rem; padding-left: 1.5rem;">
      <li>Robotic learning, manipulation, and control</li>
      <li>Machine Learning</li>
      <li>AI-based System Optimization</li>
    </ul>
    Outside of work, I enjoy <em>playing basketball, ice hockey, squash, and traveling</em>, which inspire creativity 
    and keep me energized. Feel free to connect to me for any potential opportunities or chatting!
# # =====================================================
# # üéì Education Section
# # =====================================================

education:
  - degree: "Computer Science, Visiting Undergraduate Student"
    school: "Harvard College"
    years: "2025 - 2026"
    logo: "images/harvard.png"

  - degree: "B.S. in Information Science (Minors in Robotics and AI)"
    school: "Cornell University"
    years: "2023 - 2027"
    logo: "images/Cornell.png"

# # =====================================================
# # üíº Work Experience Section
# # =====================================================

workExperience:
  - title: "Research Intern"
    company: "Stanford Artificial Intelligence Laboratory, Stanford University"
    years: "Nov 2025 - Present"
    logo: "images/Stanford_Cardinal_logo.png"

  - title: "Research Intern"
    company: "Institute for AI Industry Research (AIR), Tsinghua University"
    years: "May 2025 - August 2025"
    logo: "images/Tsinghua_University_Logo.png"

  - title: "Research Intern"
    company: "Charles Research Group, College of Engineering, Cornell University"
    years: "May 2024 - August 2024"
    logo: "images/cornelleng1.png"
    

# # =====================================================
# # üõ†Ô∏è Skills Section
# # =====================================================

skills:
  Programming:
    - name: "Python"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/200px-Python-logo-notext.svg.png"
      proficiency: Proficient
      description: null

    - name: "Java"
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Java_programming_language_logo.svg/200px-Java_programming_language_logo.svg.png"
      proficiency: Proficient
      description: null

    - name: "C/C++"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/200px-ISO_C%2B%2B_Logo.svg.png"
      proficiency: Proficient
      description: null

    - name: "R"
      logo: "images/R.png"
      proficiency: Proficient
      description: null

    - name: "MATLAB"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Matlab_Logo.png/200px-Matlab_Logo.png"
      proficiency: Advanced
      description: null

    - name: "Julia"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Julia_Programming_Language_Logo.svg/200px-Julia_Programming_Language_Logo.svg.png"
      proficiency: Advanced
      description: null

    - name: "Arduino"
      logo: "images/arduino.png"
      proficiency: Advanced
      description: null

    - name: "SQL"
      logo: "images/sql.png"
      proficiency: Advanced
      description: null

  Robotics/ML:
    - name: "PyTorch"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/PyTorch_logo_icon.svg/200px-PyTorch_logo_icon.svg.png"
      proficiency: Proficient
      description: null

    - name: "Tensorflow"
      logo: "images/tensorflow.jpg"
      proficiency: proficient
      description: null

    - name: "ROS2"
      logo: "images/ros.png"
      proficiency: proficient
      description: null

    - name: "PyDrake"
      logo: "images/pydrake.png"
      proficiency: Advanced
      description: "MIT 6.4212: Robotic Manipulation"

    - name: "SOLIDWORKS"
      logo: "images/solidworks.png"
      proficiency: Advanced
      description: null


  Online Course Certificates:
    - name: "Deep Learning Specialization"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/OOjs_UI_icon_academic-progressive.svg/200px-OOjs_UI_icon_academic-progressive.svg.png"
      proficiency: Certified by DeepLearning.AI
      description: "December 2023"

    - name: "Machine Learning Specialization"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/OOjs_UI_icon_academic-progressive.svg/200px-OOjs_UI_icon_academic-progressive.svg.png"
      proficiency: Certified by DeepLearning.AI
      description: "September 2023"

    - name: "Python for Data Science, AI & Development"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/OOjs_UI_icon_academic-progressive.svg/200px-OOjs_UI_icon_academic-progressive.svg.png"
      proficiency: Certified by IBM
      description: "July 2023"


  Web Development:
    - name: "HTML"
      logo: "images/html.png"
      proficiency: Proficient
      description: null

    - name: "JavaScript"
      logo: "images/javascript.png"
      proficiency: Proficient
      description: null

    - name: "CSS"
      logo: "images/css.png"
      proficiency: Proficient
      description: null

  Language:
    - name: "English"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/OOjs_UI_icon_language-ltr-progressive.svg/200px-OOjs_UI_icon_language-ltr-progressive.svg.png"
      proficiency: Work Proficiency
      description: null

    - name: "Mandarin"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/OOjs_UI_icon_language-ltr-progressive.svg/200px-OOjs_UI_icon_language-ltr-progressive.svg.png"
      proficiency: Native
      description: null

    - name: "French"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/OOjs_UI_icon_language-ltr-progressive.svg/200px-OOjs_UI_icon_language-ltr-progressive.svg.png"
      proficiency: Advanced
      description: null
