# =====================================================
# Data displayed on the Home (About Me) page.
#
# üí° Tip for Images / Logo:
# You can use either:
# 1. A full URL (e.g., https://example.com/logo.png)
# 2. A local file placed under /public/images/ and referenced with "/" (e.g., "/images/logo.png")
# =====================================================

# =====================================================
# üë§ Personal Information
# =====================================================

profile:
  name: "Youhui (Jeffrey) Wang"
  headline: "Student @ Harvard College | Cornell University"
  email: "jeffrey underline wang at college dot harvard dot edu"
  location: Cambridge, MA
  profileImage: "images/self.png"

  links:
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/youhuiwang/"
      icon:
        name: "FaLinkedin"
        package: "react-icons/fa6"

    - name: "Google Scholar"
      url: ""
      icon:
        name: "FaGoogleScholar"
        package: "react-icons/fa6"

    - name: "R√©sum√©"
      url: ""
      icon:
        name: "FaRegIdBadge"
        package: "react-icons/fa6"

    - name: "Github"
      url: "https://github.com/JeffreyWang060303"
      icon:
        name: "FaGithub"
        package: "react-icons/fa6"

  # you can use HTML syntax here (e.g. <br/>, <a>, <strong>, ...)
  biography: |
    Hi! I'm <strong>Jeffrey Wang</strong>, currently a Visiting Undergraduate Student at <em>Harvard College</em> 
    passionate about <em>Robotics learning, control, and Artificial Intelligence in general</em>. 
    Currently, I work as a <em>Research Assistant</em> at the <em>CogAI Lab under Stanford Aritficial 
    Intelligence Laboratory, fortunately advised by Raven Huang, Prof. Jiajun Wu, and Prof. Fei-fei Li,
    and Harvard Edge Computing Lab</em>, fortunately advised by Jason Jabbour and Prof. Vijay Janapa Reddi.
    With a background in <em>Information Science at Cornell University</em>, I've developed strong interests in 
    <em>Robotics, Machine Learning, and AI</em> and have contributed to projects like <i>Sim2RealGen</i> and <i>GLUSTICK</i>, 
    all focused on <em>enhancing robotic safety and real-world manipulation</em>.
    <div class="my-2"></div>
    Outside of work, I enjoy <em>Ice Hockey, Squash, and Traveling</em>, which inspire creativity 
    and keep me energized. Feel free to connect to me for any potential opportunities or chatting!
# # =====================================================
# # üéì Education Section
# # =====================================================

education:
  - degree: "Visiting Undergraduate Student"
    school: "Harvard College"
    years: "2025 - 2026"
    logo: "images/harvard.png"

  - degree: "B.S. in Information Science (Minors in Robotics and AI)"
    school: "Cornell University"
    years: "2023 - 2027"
    logo: "images/Cornell.png"

# # =====================================================
# # üíº Work Experience Section
# # =====================================================

workExperience:
  - title: "Research Intern"
    company: "Stanford Vision and Learning Lab, Stanford University"
    years: "Nov 2025 - Present"
    logo: "images/Stanford_Cardinal_logo.png"

  - title: "Research Intern"
    company: "Institute for AI Industry Research (AIR), Tsinghua University"
    years: "May 2025 - August 2025"
    logo: "images/Tsinghua_University_Logo.png"

# # =====================================================
# # üõ†Ô∏è Skills Section
# # =====================================================

# # =====================================================
# # üõ†Ô∏è Skills Section
# # =====================================================

skills:
  Programming:
    - name: "Python"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/200px-Python-logo-notext.svg.png"
      proficiency: Proficient
      description: null

    - name: "Java"
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Java_programming_language_logo.svg/200px-Java_programming_language_logo.svg.png"
      proficiency: Proficient
      description: null

    - name: "C/C++"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/200px-ISO_C%2B%2B_Logo.svg.png"
      proficiency: Proficient
      description: null

    - name: "R"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Matlab_Logo.png/200px-Matlab_Logo.png"
      proficiency: Proficient
      description: null

    - name: "MATLAB"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Matlab_Logo.png/200px-Matlab_Logo.png"
      proficiency: Advanced
      description: null

    - name: "Julia"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Julia_Programming_Language_Logo.svg/200px-Julia_Programming_Language_Logo.svg.png"
      proficiency: Advanced
      description: null

    - name: "SQL"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Matlab_Logo.png/200px-Matlab_Logo.png"
      proficiency: Advanced
      description: null

  Robotics/ML:
    - name: "PyTorch"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/PyTorch_logo_icon.svg/200px-PyTorch_logo_icon.svg.png"
      proficiency: Proficient
      description: null

    - name: "Tensorflow"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/OOjs_UI_icon_academic-progressive.svg/200px-OOjs_UI_icon_academic-progressive.svg.png"
      proficiency: proficient
      description: null

    - name: "PyDrake"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/OOjs_UI_icon_academic-progressive.svg/200px-OOjs_UI_icon_academic-progressive.svg.png"
      proficiency: Advanced
      description: "MIT 6.4212: Robotic Manipulation"

    - name: "SOLIDWORKS"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/OOjs_UI_icon_academic-progressive.svg/200px-OOjs_UI_icon_academic-progressive.svg.png"
      proficiency: Advanced
      description: "MIT 6.4212: Robotic Manipulation"


  Online Course Certificates:
    - name: "Robotics"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/OOjs_UI_icon_academic-progressive.svg/200px-OOjs_UI_icon_academic-progressive.svg.png"
      proficiency: 2024 - Now
      description: "Bio-inspired robots, aerial microrobotics, and compliant manipulation."

    - name: "Deep Learning"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/OOjs_UI_icon_academic-progressive.svg/200px-OOjs_UI_icon_academic-progressive.svg.png"
      proficiency: 2023 - Now
      description: "Offline RL, VLA models, and representation learning."


  Web:
    - name: "HTML"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/200px-React-icon.svg.png"
      proficiency: Proficient
      description: null

    - name: "JavaScript"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/200px-React-icon.svg.png"
      proficiency: Proficient
      description: null

    - name: "CSS"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/200px-React-icon.svg.png"
      proficiency: Proficient
      description: null

  Language:
    - name: "English"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/OOjs_UI_icon_language-ltr-progressive.svg/200px-OOjs_UI_icon_language-ltr-progressive.svg.png"
      proficiency: Work Proficiency
      description: null

    - name: "Mandarin"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/OOjs_UI_icon_language-ltr-progressive.svg/200px-OOjs_UI_icon_language-ltr-progressive.svg.png"
      proficiency: Native
      description: null