# =====================================================
# Sidebar Layout Configuration
#
# - The order of sections below determines their display order in the sidebar.
# - To remove a page from the sidebar, simply delete the corresponding item.
# =====================================================

sidebar:
  userName: "Youhui (Jeffrey) Wang" # Name displayed at the top of the sidebar
  profileImage: images/self3.png # Profile image URL
  sections:
    - title: About Me
      url: ""
      icon:
        name: LuUser
        package: "react-icons/lu"

    - title: Projects
      url: "projects"
      icon:
        name: LuWrench
        package: "react-icons/lu"

    - title: Publications
      url: "publications"
      icon:
        name: LuLibraryBig
        package: "react-icons/lu"
    
    - title: Skills
      url: "skills"
      icon:
        name: LuLibraryBig
        package: "react-icons/lu"

    - title: Courseworks
      url: "courseworks"
      icon:
        name: LuBook
        package: "react-icons/lu"

  
